[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/selfhosted.Dockerfile"

[deploy]
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
